modLoader="javafml"
loaderVersion="[47,)"
license="MIT <- U CAN CHANGE"

[[mods]]
modId="template"
version="1.0-SNAPSHOT"
displayName="TEMPLATE"
logoFile="icon.png"
authors="Akaize, SweetB1ans <- U CAN CHANGE"
description="""
"""

[[dependencies.template]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.template]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

