modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="glze"
version="1"
displayName="Glaze"
logoFile="icon.png"
authors="Akaize"
description="""
"""

[[dependencies.glze]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.glze]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

