plugins {
    id 'fabric-loom'
}

base {
    archivesName = "${project.archives_base_name}-fabric"
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    mappings loom.layered() {
        officialMojangMappings()
        def pMc = project.findProperty('parchment_mc_version') ?: project.minecraft_version
        def pVer = project.findProperty('parchment_version') ?: ''
        if (pVer) {
            parchment("org.parchmentmc.data:parchment-${pMc}:${pVer}@zip")
        }
    }

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

    def mixinExtrasVer = project.findProperty('mixinextras_version') ?: '0.4.1'
    compileOnly "io.github.llamalad7:mixinextras-common:${mixinExtrasVer}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixinExtrasVer}"
    annotationProcessor "org.spongepowered:mixin:${project.mixin_version}:processor"
}

tasks.named('processResources', ProcessResources).configure {
    inputs.properties rootProject.ext.modProperties

    filesMatching('fabric.mod.json') {
        expand rootProject.ext.modProperties
    }
}

tasks.named('jar', Jar).configure {
    archiveFileName.set("${project.archives_base_name}-${project.mod_version}-fabric-dev.jar")
    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
}

tasks.named('remapJar').configure {
    archiveFileName.set("${project.archives_base_name}-${project.mod_version}-fabric.jar")
    destinationDirectory.set(layout.buildDirectory.dir("libs"))

    from {
        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
    }

    if (file("LICENSE").exists()) {
        from("LICENSE") {
            rename { "${it}_${project.base.archivesName.get()}" }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-AmodLoaderTarget=fabric"
}