#gradle things
org.gradle.parallel=true
org.gradle.caching=true
systemProp.http.userAgent=Gradle
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:+ParallelRefProcEnabled

publishing_url=

aslib_version=Dev_1.20.1-SNAPSHOT
dbuild_version=1.0-SNAPSHOT

#mod meta
mod_id=glz
mod_version=1.0-SNAPSHOT
mod_name=Glaze + GlazeLib
mod_description=look, now anything is different!
mod_authors=Akaize
mod_license=MIT
mod_homepage=https://github.com/Akfz/DBuild
mod_issues=
mod_icon=assets/glze/icon.png

maven_group=v.akfz
archives_base_name=glze
#you need to rename for work mixins
mixin_name=glaze.mixins

#minecraft data
java_version=17
minecraft_version=1.20.1

#mappings
mojang_mappings=1.20.1
parchment_mc_version=1.20.1
parchment_version=2023.09.03

#loaders settings
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=6.0.53

neoforge_version=20.4.251
neoforge_gradle_version=2.0.78

#mixin
mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT
mixinextras_version=0.4.1