org.gradle.jvmargs=-Xmx4G

# Meta of mod
# change in all .gradle or write mixins like mod_id.mixins.json (like aslib.mixins.json)
mod_id=template
mod_version=1.0-SNAPSHOT
mod_name=TEMPLATE
mod_description=
mod_authors=Akaize, SweetB1ans <- U CAN CHANGE
mod_license=MIT <- U CAN CHANGE
mod_homepage=
mod_issues=
mod_icon=assets/template/icon.png

maven_group=n.paradox
#archives_base_name - mostly its modid
archives_base_name=template

minecraft_version=1.20.1
mojang_mappings=1.20.1

# dont change if u dont understand
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=6.0.53

quilt_loom_version=1.4.1
quilt_loader_version=0.21.0

neoforge_version=2.0.91

mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT