org.gradle.jvmargs=-Xmx4G

# Meta of mod
mod_id=glze
mod_version=1
mod_name=Glaze
mod_description=
mod_authors=Akaize
mod_license=MIT
mod_homepage=
mod_issues=Light!!! To be honest, mod is not ready
mod_icon=assets/glze/icon.png

maven_group=v.akfz
archives_base_name=glze

minecraft_version=1.20.1
mojang_mappings=1.20.1

fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=6.0.53

neoforge_version=2.0.91

mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT