plugins {
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${project.archives_base_name}-neoforge"
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
}

neoForge {
    version = project.neoforge_version

    def pVer = project.findProperty('parchment_version') ?: '2024.03.03'
    def pMc = project.findProperty('parchment_mc_version') ?: project.minecraft_version
    if (pVer) {
        parchment {
            mappingsVersion = pVer
            minecraftVersion = pMc
        }
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    def mixinExtrasVer = project.findProperty('mixinextras_version') ?: '0.4.1'
    compileOnly "io.github.llamalad7:mixinextras-common:${mixinExtrasVer}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixinExtrasVer}"
    annotationProcessor "org.spongepowered:mixin:${project.mixin_version}:processor"
}

tasks.named('processResources', ProcessResources).configure {
    inputs.properties rootProject.ext.modProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand rootProject.ext.modProperties
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output

    from {
        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
    }

    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveFileName.set("${project.archives_base_name}-${project.mod_version}-neoforge.jar")

    manifest {
        attributes([
                "Specification-Title"     : project.mod_id,
                "Specification-Vendor"    : project.maven_group,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.mod_version,
                "Implementation-Vendor"   : project.maven_group,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.register('devJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output

    from {
        configurations.embed.collect { it.isDirectory() ? it : zipTree(it) }
    }

    destinationDirectory.set(layout.buildDirectory.dir("libs"))
    archiveFileName.set("${project.archives_base_name}-${project.mod_version}-neoforge-dev.jar")

    manifest {
        attributes([
                "Specification-Title"     : project.mod_id,
                "Specification-Vendor"    : project.maven_group,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.mod_version,
                "Implementation-Vendor"   : project.maven_group,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-AmodLoaderTarget=neoforge"
}